# Generated by Django 4.2.23 on 2025-06-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famcircle', '0001_initial'),
        ('nucfamily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuclearfamily',
            name='circles',
            field=models.ManyToManyField(blank=True, related_name='families', to='famcircle.familycircle'),
        ),
    ]
