# Generated by Django 4.2.23 on 2025-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucfamily', '0002_nuclearfamily_circles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuclearfamily',
            name='circles',
        ),
        migrations.AddField(
            model_name='familymembership',
            name='can_join_circles',
            field=models.BooleanField(default=False, verbose_name='Может присоединяться к кругам'),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='can_manage_circle_access',
            field=models.BooleanField(default=False, verbose_name='Может управлять доступом к кругам'),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='can_share_to_circles',
            field=models.BooleanField(default=False, verbose_name='Может делиться данными с кругами'),
        ),
    ]
