# Generated by Django 4.2.23 on 2025-06-27 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название круга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('join_code', models.CharField(max_length=32, unique=True, verbose_name='Код для присоединения')),
                ('join_password', models.CharField(max_length=128, verbose_name='Пароль для присоединения (хэш)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='CircleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('member', 'Участник')], default='member', max_length=16, verbose_name='Роль')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('invited', 'Приглашён'), ('left', 'Покинул')], default='active', max_length=16, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='famcircle.familycircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Член семейного круга',
                'verbose_name_plural': 'Члены семейного круга',
                'unique_together': {('user', 'circle')},
            },
        ),
    ]
