# Generated by Django 4.2.23 on 2025-06-29 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucfamily', '0003_remove_nuclearfamily_circles_and_more'),
        ('famcircle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleFamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('member', 'Участник')], default='member', max_length=16, verbose_name='Роль семьи')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('invited', 'Приглашён'), ('left', 'Покинул')], default='active', max_length=16, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_families_to_circles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство семьи в круге',
                'verbose_name_plural': 'Членства семей в кругах',
            },
        ),
        migrations.AddField(
            model_name='familycircle',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='circles', to='nucfamily.nuclearfamily'),
        ),
        migrations.DeleteModel(
            name='CircleMembership',
        ),
        migrations.AddField(
            model_name='circlefamilymembership',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='famcircle.familycircle'),
        ),
        migrations.AddField(
            model_name='circlefamilymembership',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterUniqueTogether(
            name='circlefamilymembership',
            unique_together={('family', 'circle')},
        ),
    ]
