# Generated by Django 4.2.23 on 2025-06-26 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_family_role_subscriptionplan_usersubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость покупки')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Текущая стоимость')),
                ('last_valuation_date', models.DateField(auto_now=True, verbose_name='Дата последней оценки')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейный актив')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейная категория')),
                ('type', models.CharField(choices=[('asset', 'Актив'), ('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='users.family')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Символ')),
                ('is_default', models.BooleanField(default=False, verbose_name='Встроенная валюта')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'currencies',
                'unique_together': {('code', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='LiabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа')),
                ('is_base', models.BooleanField(default=False, verbose_name='Базовый тип')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_types', to='users.family')),
            ],
            options={
                'verbose_name': 'Тип пассива',
                'verbose_name_plural': 'Типы пассивов',
                'db_table': 'liability_types',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Первоначальная сумма')),
                ('open_date', models.DateField(verbose_name='Дата открытия')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ставка % годовых')),
                ('payment_type', models.CharField(blank=True, choices=[('annuity', 'Аннуитетный'), ('diff', 'Дифференцированный')], max_length=20, null=True, verbose_name='Способ погашения')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата платежа')),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Задолженность на сегодня')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейный пассив')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='finance.currency')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='users.family')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='finance.liabilitytype')),
            ],
            options={
                'verbose_name': 'Пассив/Обязательство',
                'verbose_name_plural': 'Пассивы/Обязательства',
                'db_table': 'liabilities',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('type', models.CharField(choices=[('regular', 'Постоянный'), ('temporary', 'Временный'), ('occasional', 'Случайный')], max_length=20, verbose_name='Вид')),
                ('periodicity', models.CharField(blank=True, max_length=30, verbose_name='Периодичность')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейный доход')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='finance.asset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='finance.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.currency')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='users.family')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'db_table': 'incomes',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название фонда')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цель накопления')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Целевая дата')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Текущая сумма')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейный фонд')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='users.family')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
                'db_table': 'funds',
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Целевая сумма')),
                ('target_date', models.DateField(verbose_name='Целевая дата')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейная цель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_goals', to='users.family')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Финансовая цель',
                'verbose_name_plural': 'Финансовые цели',
                'db_table': 'financial_goals',
            },
        ),
        migrations.CreateModel(
            name='FinanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID сущности')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='Данные до')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='Данные после')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог финансового блока',
                'verbose_name_plural': 'Логи финансового блока',
                'db_table': 'finance_logs',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('type', models.CharField(choices=[('mandatory', 'Обязательный'), ('optional', 'Необязательный')], max_length=20, verbose_name='Тип')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейный расход')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.asset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.currency')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='users.family')),
                ('liability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.liability')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='Период')),
                ('planned_income', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Планируемый доход')),
                ('planned_expense', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Планируемый расход')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейный бюджет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='users.family')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'db_table': 'budget_plans',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа')),
                ('is_base', models.BooleanField(default=False, verbose_name='Базовый тип')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='users.family')),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': 'Типы активов',
                'db_table': 'asset_types',
            },
        ),
        migrations.CreateModel(
            name='AssetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Доля')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='finance.asset')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_shares', to='users.family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доля актива',
                'verbose_name_plural': 'Доли активов',
                'db_table': 'asset_shares',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='finance.category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_current', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='asset',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='users.family'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_purchase', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='finance.assettype'),
        ),
        migrations.CreateModel(
            name='LiabilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма платежа')),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Погашение основного долга')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Погашение процентов')),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.liability')),
            ],
            options={
                'verbose_name': 'Платеж по пассиву',
                'verbose_name_plural': 'Платежи по пассивам',
                'db_table': 'liability_payments',
                'unique_together': {('liability', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate_to_base', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Курс к базовой валюте')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.currency')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'currency_rates',
                'unique_together': {('currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssetValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Оценочная стоимость')),
                ('date', models.DateField(verbose_name='Дата оценки')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='finance.asset')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
            ],
            options={
                'verbose_name': 'История стоимости актива',
                'verbose_name_plural': 'Истории стоимости активов',
                'db_table': 'asset_value_history',
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
