# Generated by Django 4.2.23 on 2025-07-01 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nucfamily', '0003_remove_nuclearfamily_circles_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liabilitypayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liabilitypayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='assetshare',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_shares', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='budgetplan',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='category',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_goals', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='income',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='nucfamily.nuclearfamily'),
        ),
        migrations.AlterField(
            model_name='liabilitytype',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_types', to='nucfamily.nuclearfamily'),
        ),
    ]
