# Generated by Django 4.2.23 on 2025-07-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financelog_created_at_financelog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней оценки'),
        ),
    ]
