# Generated by Django 4.2.23 on 2025-07-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_asset_last_valuation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Разовый'), ('monthly', 'Ежемесячно'), ('weekly', 'Еженедельно')], default='none', help_text='Тип повторения расхода', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_valuation_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата последней оценки'),
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(auto_now_add=True, help_text='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Оплаченная сумма', max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.expense')),
            ],
            options={
                'verbose_name': 'Оплата расхода',
                'verbose_name_plural': 'Оплаты расходов',
                'db_table': 'expense_payments',
            },
        ),
    ]
