# Generated by Django 4.2.23 on 2025-06-27 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_family_role_subscriptionplan_usersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость имени')),
                ('last_name_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость фамилии')),
                ('middle_name_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость отчества')),
                ('birth_date_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость даты рождения')),
                ('phone_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость телефона')),
                ('email_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость email')),
                ('avatar_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость аватара')),
                ('bio_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость биографии')),
                ('address_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость адреса')),
                ('company_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость компании')),
                ('position_visibility', models.CharField(choices=[('personal', 'Личное'), ('family', 'Семья'), ('circle', 'Круг')], default='personal', max_length=16, verbose_name='Видимость должности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_visibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Видимость данных пользователя',
                'verbose_name_plural': 'Видимость данных пользователей',
                'db_table': 'user_data_visibility',
            },
        ),
    ]
