# Generated by Django 4.2.23 on 2025-06-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdatavisibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymembership',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
